openapi: 3.0.0
info:
  title: Sample API
  version: 0.1.0
paths:
  '/books':
    get:
      responses:
        '200':
          description: ok
          content:
            'application/json':
              schema:
                type: object
                properties:
                  books:
                    type: array
                    items:
                      allOf:
                        - $ref: '#/components/schemas/ModelBase'
                        - type: object
                          properties:
                            title:
                              type: string
                            publisher:
                              $ref: '#/components/schemas/Publisher'
                          required:
                            - id
                            - title
                            - publisher
                          additionalProperties: false
components:
  schemas:
    Publisher:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
      required:
        - id
        - name
      additionalProperties: false
    ModelBase:
      type: object
      properties:
        id:
          type: integer
      required: [id]
      additionalProperties: false
